[package]
name = "fmwasm"
version = "0.1.0"
authors = ["Seiichi KONDO <seikichi@kmc.gr.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
suffix = "1"

# for wasm
wasm-bindgen = "0.2"
